<a href="https://colab.research.google.com/github/karthickthangadurai/Guvi_Task_2/blob/main/Numpy_tasks_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy



#### 1. Import the numpy package under the name `np` (★☆☆) 
(**hint**: import … as …)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆) 
(**hint**: np.\_\_version\_\_, np.show\_config)

In [2]:
np.__version__,np.show_config

('1.21.6', <function numpy.__config__.show>)

#### 3. Create a null vector of size 10 (★☆☆) 
(**hint**: np.zeros)

In [3]:
a=np.zeros(10)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4.  How to find the memory size of any array (★☆☆) 
(**hint**: size, itemsize)

In [4]:
print(a.size)
print(a.itemsize)

10
8


#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆) 
(**hint**: np.info)

In [5]:
np.info(np.sum)

 sum(a, axis=None, dtype=None, out=None, keepdims=<no value>,
     initial=<no value>, where=<no value>)

Sum of array elements over a given axis.

Parameters
----------
a : array_like
    Elements to sum.
axis : None or int or tuple of ints, optional
    Axis or axes along which a sum is performed.  The default,
    axis=None, will sum all of the elements of the input array.  If
    axis is negative it counts from the last to the first axis.

    .. versionadded:: 1.7.0

    If axis is a tuple of ints, a sum is performed on all of the axes
    specified in the tuple instead of a single axis or all the axes as
    before.
dtype : dtype, optional
    The type of the returned array and of the accumulator in which the
    elements are summed.  The dtype of `a` is used by default unless `a`
    has an integer dtype of less precision than the default platform
    integer.  In that case, if `a` is signed then the platform integer
    is used while if `a` is unsigned then an unsigned integer 

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆) 
(**hint**: array\[4\])

In [6]:
b=np.arange(1,11)
print(b)
b[4]=1
b

[ 1  2  3  4  5  6  7  8  9 10]


array([ 1,  2,  3,  4,  1,  6,  7,  8,  9, 10])

#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆) 
(**hint**: np.arange)

In [7]:
c=np.arange(10,50)
c

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8.  Reverse a vector (first element becomes last) (★☆☆) 
(**hint**: array\[::-1\])

In [8]:
c[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆) 
(**hint**: reshape)

In [9]:
d=np.arange(0,9).reshape(3,3)
d

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆) 
(**hint**: np.nonzero)

In [10]:
e=[1,2,0,0,4,0]
np.nonzero(e)

(array([0, 1, 4]),)

#### 11. Create a 3x3 identity matrix (★☆☆) 
(**hint**: np.eye)

In [11]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆) 
(**hint**: np.random.random)

In [12]:
np.random.random((3,3,3))

array([[[0.66651337, 0.59088349, 0.24420842],
        [0.55068274, 0.61187053, 0.48542523],
        [0.89382255, 0.49896985, 0.04081917]],

       [[0.08073556, 0.67048901, 0.80337858],
        [0.16073434, 0.31470397, 0.97061053],
        [0.7149343 , 0.6714919 , 0.88078283]],

       [[0.02927476, 0.57928961, 0.12750316],
        [0.17692203, 0.83371541, 0.00638616],
        [0.99832121, 0.24401559, 0.89003452]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆) 
(**hint**: min, max)

In [13]:
e=np.random.random((10,10))
print(e)
print(e.min(),e.max())

[[0.36707695 0.31504803 0.69011365 0.63705846 0.79823768 0.36036033
  0.60936634 0.51260077 0.96488363 0.69269688]
 [0.9569817  0.63366896 0.62336131 0.74531925 0.52963655 0.75453823
  0.4486339  0.75440253 0.9719722  0.79461193]
 [0.63395605 0.33177971 0.69156284 0.35658754 0.41043532 0.16223487
  0.45400048 0.44508791 0.17802278 0.11618133]
 [0.07511737 0.86796184 0.26301923 0.23354893 0.9141019  0.65801122
  0.14285031 0.49886517 0.08697622 0.33591708]
 [0.9813537  0.61226372 0.96947416 0.86281964 0.94584115 0.232065
  0.51618173 0.22357584 0.7822459  0.68328667]
 [0.12159265 0.30421181 0.66687335 0.27041072 0.99749491 0.374936
  0.37239732 0.87897664 0.17915645 0.66776017]
 [0.09814153 0.727783   0.29317389 0.26139366 0.21406756 0.38365218
  0.93660474 0.48405844 0.14311504 0.07513644]
 [0.36792683 0.09094838 0.31327836 0.29142052 0.42664172 0.72736875
  0.45222463 0.60505258 0.64985018 0.84585725]
 [0.7492621  0.65987238 0.58494606 0.43564902 0.53721289 0.67003886
  0.82248628 0.9

#### 14. Create a random vector of size 30 and find the mean value (★☆☆) 
(**hint**: mean)

In [14]:
f=np.random.random(30)
f.mean()

0.4397129281115734

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆) 
(**hint**: array\[1:-1, 1:-1\])

In [15]:
g=np.ones((5,5))
print(g)
g[1:-1,1:-1]=0
g

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆) 
(**hint**: np.pad)

In [16]:
print(g)
np.pad(g,pad_width=2,mode="constant",constant_values=0)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 0., 0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0., 0., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

#### 17. What is the result of the following expression? (★☆☆) 
(**hint**: NaN = not a number, inf = infinity)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1
```

In [17]:
print(0*np.nan)
print(np.nan==np.nan)
print(np.inf>np.nan)
print(np.nan-np.nan)
print(0.3==3*0.1)

nan
False
False
nan
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆) 
(**hint**: np.diag)

In [18]:
np.diag([1,2,3,4],k=-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆) 
(**hint**: array\[::2\])

In [19]:
g=np.ones((8,8))
g[1::2,::2]=0
g[::2,1::2]=0
g

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? 
(**hint**: np.unravel_index)

In [20]:
np.unravel_index(100,(6,7,8))

(1, 5, 4)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆) 
(**hint**: np.tile)

In [21]:
np.tile(np.array([[0,1],[1,0]]),(4,4))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 22. Normalize a 5x5 random matrix (★☆☆) 
(**hint**: (x - min) / (max - min))

In [22]:
x=np.random.random((5,5))
print(x)
(x-x.min())/(x.max()-x.max())

[[0.79030252 0.75566893 0.38034464 0.31205476 0.27278995]
 [0.7104213  0.37271265 0.42449807 0.03995734 0.38626959]
 [0.12141737 0.60953733 0.27143424 0.20364684 0.54084562]
 [0.70328128 0.00914082 0.24084646 0.5671062  0.80222882]
 [0.36384494 0.69660349 0.10337046 0.45944017 0.85677324]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: RuntimeWarning: divide by zero encountered in true_divide
  This is separate from the ipykernel package so we can avoid doing imports until
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: RuntimeWarning: invalid value encountered in true_divide
  This is separate from the ipykernel package so we can avoid doing imports until


array([[inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf],
       [inf, nan, inf, inf, inf],
       [inf, inf, inf, inf, inf]])

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆) 
(**hint**: np.dtype)

In [23]:
RGBA = np.dtype([('r',np.uint8),('g',np.uint8),('b',np.uint8),('a',np.uint8)])
color = np.array((1,2,3,4),dtype = RGBA)
print(color['a'])
type(color)

4


numpy.ndarray

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆) 
(**hint**: np.dot | @)

In [24]:
x=np.random.random((5,3))
y=np.random.random((3,2))
np.dot(x,y)

array([[0.09971936, 0.40120122],
       [0.24429464, 0.35509002],
       [0.18860745, 0.59818591],
       [0.1221576 , 0.34328313],
       [0.03385604, 0.28248234]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆) 
(**hint**: >, <=)

In [25]:
m=np.arange(1,11)
print(m)
m[(3<m)&(m<8)]*=-1
m

[ 1  2  3  4  5  6  7  8  9 10]


array([ 1,  2,  3, -4, -5, -6, -7,  8,  9, 10])

#### 26. What is the output of the following script? (★☆☆) 
(**hint**: np.sum)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [26]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [27]:
z=arange(1,10)
print(z**z)
print(2<<z<<2)
print(z<-z)
print(1j*z)
print(z/1/1)
# print(z<z<z)

[        1         4        27       256      3125     46656    823543
  16777216 387420489]
[  16   32   64  128  256  512 1024 2048 4096]
[False False False False False False False False False]
[0.+1.j 0.+2.j 0.+3.j 0.+4.j 0.+5.j 0.+6.j 0.+7.j 0.+8.j 0.+9.j]
[1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [28]:
np.array(0)/np.array(0)
np.array(0)//np.array(0)
np.array([np.nan]).astype(int).astype(float)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  


array([-9.22337204e+18])

#### 29. How to round away from zero a float array ? (★☆☆) 
(**hint**: np.uniform, np.copysign, np.ceil, np.abs)

In [29]:
j=np.random.uniform(-8,8,5)
print(j)
np.copysign(j,+2)
np.abs(j)
np.ceil(j)#round

[ 0.04525219 -1.53850996 -6.95184958  5.52338935 -3.46655225]


array([ 1., -1., -6.,  6., -3.])

#### 30. How to find common values between two arrays? (★☆☆) 
(**hint**: np.intersect1d)

In [30]:
k=np.arange(1,10)
l=np.arange(6,15)
np.intersect1d(k,l)


array([6, 7, 8, 9])

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆) 
(**hint**: np.seterr, np.errstate)

In [31]:
print(np.seterr())
np.errstate()

{'divide': 'warn', 'over': 'warn', 'under': 'ignore', 'invalid': 'warn'}


#### 32. Is the following expressions true? (★☆☆) 
(**hint**: imaginary number)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [32]:
np.sqrt(-1) == np.emath.sqrt(-1)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆) 
(**hint**: np.datetime64, np.timedelta64)

In [33]:
y = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yesterday: ",y)
t     = np.datetime64('today', 'D')
print("Today: ",t)
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow: ",tomorrow)

Yesterday:  2022-05-13
Today:  2022-05-14
Tomorrow:  2022-05-15


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆) 
(**hint**: np.arange(dtype=datetime64\['D'\]))

In [34]:
np.arange("2016-07","2016-08",dtype='datetime64[D]')

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆) 
(**hint**: np.add(out=), np.negative(out=), np.multiply(out=), np.divide(out=))

In [35]:
p=np.ones(3)*2
q=np.ones(3)*3
np.multiply((np.add(p,q)),np.divide(np.negative(p),2))


array([-5., -5., -5.])

#### 36. Extract the integer part of a random array using 5 different methods (★★☆) 
(**hint**: %, np.floor, np.ceil, astype, np.trunc)

In [36]:
o=np.linspace(1,10,5)
print(o)
print(o-o%2)
print(np.floor(o))
print(np.ceil(o))
print(np.trunc(o))
print(o.astype(complex))


[ 1.    3.25  5.5   7.75 10.  ]
[ 0.  2.  4.  6. 10.]
[ 1.  3.  5.  7. 10.]
[ 1.  4.  6.  8. 10.]
[ 1.  3.  5.  7. 10.]
[ 1.  +0.j  3.25+0.j  5.5 +0.j  7.75+0.j 10.  +0.j]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆) 
(**hint**: np.arange)

In [37]:
s=np.tile(np.arange(0,5),(5,1))
print(s)
s.shape

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


(5, 5)

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆) 
(**hint**: np.fromiter)

In [38]:
def generator():
  for i in range(0,10):
        yield i
np.fromiter(generator(),dtype=int)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆) 
(**hint**: np.linspace)

In [39]:
np.linspace(0,1,12,endpoint=True)[1:-1]

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

#### 40. Create a random vector of size 10 and sort it (★★☆) 
(**hint**: sort)

In [40]:
rv=np.random.randint(20,size=10)
rv.sort()
s

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

#### 41. How to sum a small array faster than np.sum? (★★☆) 
(**hint**: np.add.reduce)

In [41]:
np.add.reduce(np.arange(27).reshape((3,3,3)),0)

array([[27, 30, 33],
       [36, 39, 42],
       [45, 48, 51]])

#### 42. Consider two random array A and B, check if they are equal (★★☆) 
(**hint**: np.allclose, np.array\_equal)

In [42]:
A=np.random.randint(10,20,5)
B=np.random.randint(10,20,5)
np.array_equal(A,B)

False

#### 43. Make an array immutable (read-only) (★★☆) 
(**hint**: flags.writeable)

In [43]:
z=np.arange(0,10)
print(z)
z.flags.writeable=False
# z[2]=100
z

[0 1 2 3 4 5 6 7 8 9]


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆) 
(**hint**: np.sqrt, np.arctan2)

In [44]:
# To convert from Cartesian Coordinates (x,y) to Polar Coordinates (r,θ):
# r = √ ( x2 + y2 )
# θ = tan-1 ( y / x )
a=np.random.random((10,2))
x,y=a[:,0],a[:,1]
r=np.sqrt(x**2 + y**2)
Deg=np.arctan2(y,x)
print(r)
print(Deg)

[1.04661852 0.98790949 0.74934206 1.01654482 0.96254571 0.94886421
 0.36837616 0.42192972 0.67592109 0.76240218]
[1.14901933 0.57588124 0.50735632 0.66473968 0.41815409 1.51989437
 0.26447248 1.34629092 1.1832553  1.09833458]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆) 
(**hint**: argmax)

In [45]:
m=np.random.randint(10,30,10)
print(m)
m[argmax(m)]=0
m

[24 23 10 17 15 26 10 24 23 26]


array([24, 23, 10, 17, 15,  0, 10, 24, 23, 26])

#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆) 
(**hint**: np.meshgrid)

In [46]:
Z = np.ones((5,5), [('x',int),('y',int)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),np.linspace(0,1,5))
print(Z)

[[(0, 0) (0, 0) (0, 0) (0, 0) (1, 0)]
 [(0, 0) (0, 0) (0, 0) (0, 0) (1, 0)]
 [(0, 0) (0, 0) (0, 0) (0, 0) (1, 0)]
 [(0, 0) (0, 0) (0, 0) (0, 0) (1, 0)]
 [(0, 1) (0, 1) (0, 1) (0, 1) (1, 1)]]


####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) 
(**hint**: np.subtract.outer)

In [47]:
X = np.arange(1,5).reshape(2,2)
print(X)
Y = np.arange(5,9).reshape(2,2)
print(Y)
C = (1/(np.subtract.outer(X,Y)))
C

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


array([[[[-0.25      , -0.2       ],
         [-0.16666667, -0.14285714]],

        [[-0.33333333, -0.25      ],
         [-0.2       , -0.16666667]]],


       [[[-0.5       , -0.33333333],
         [-0.25      , -0.2       ]],

        [[-1.        , -0.5       ],
         [-0.33333333, -0.25      ]]]])

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆) 
(**hint**: np.iinfo, np.finfo, eps)

In [48]:
for dtype in [np.int8,np.int16, np.int32, np.int64]:
   print(np.iinfo(dtype).min,np.iinfo(dtype).max)
for dtype in [np.float16,np.float32, np.float64]:
   print(np.finfo(dtype).min,np.finfo(dtype).max,np.finfo(dtype).eps)

-128 127
-32768 32767
-2147483648 2147483647
-9223372036854775808 9223372036854775807
-65500.0 65500.0 0.000977
-3.4028235e+38 3.4028235e+38 1.1920929e-07
-1.7976931348623157e+308 1.7976931348623157e+308 2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆) 
(**hint**: np.set\_printoptions)

In [49]:
np.set_printoptions(precision=2,threshold=None)
C


array([[[[-0.25, -0.2 ],
         [-0.17, -0.14]],

        [[-0.33, -0.25],
         [-0.2 , -0.17]]],


       [[[-0.5 , -0.33],
         [-0.25, -0.2 ]],

        [[-1.  , -0.5 ],
         [-0.33, -0.25]]]])

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆) 
(**hint**: argmin)

In [50]:
c=np.arange(100)
d=np.random.uniform(0,100)
print(d)
index=(np.abs(c-d)).argmin()
print(c[index])

52.96416860553171
53


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆) 
(**hint**: dtype)

In [51]:
np.ones(10,[('position',[('x',float,1),
                            ('y',float,1)]),
               ('color',[('r',float,1),
                         ('g',float,1),
                         ('b',float,1)])])

/usr/local/lib/python3.7/dist-packages/numpy/core/numeric.py:204: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  a = empty(shape, dtype, order)


array([((1., 1.), (1., 1., 1.)), ((1., 1.), (1., 1., 1.)),
       ((1., 1.), (1., 1., 1.)), ((1., 1.), (1., 1., 1.)),
       ((1., 1.), (1., 1., 1.)), ((1., 1.), (1., 1., 1.)),
       ((1., 1.), (1., 1., 1.)), ((1., 1.), (1., 1., 1.)),
       ((1., 1.), (1., 1., 1.)), ((1., 1.), (1., 1., 1.))],
      dtype=[('position', [('x', '<f8'), ('y', '<f8')]), ('color', [('r', '<f8'), ('g', '<f8'), ('b', '<f8')])])

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆) 
(**hint**: np.atleast\_2d, T, np.sqrt)

In [52]:
rv=np.random.random((100,2))
x,y=np.atleast_2d(rv[:,0],rv[:,1])
d=np.sqrt((x-x.T)**2 +(y-y.T)**2)
print(d)

[[0.   0.78 0.64 ... 0.3  0.41 0.74]
 [0.78 0.   0.43 ... 0.58 0.64 0.05]
 [0.64 0.43 0.   ... 0.61 0.75 0.4 ]
 ...
 [0.3  0.58 0.61 ... 0.   0.16 0.53]
 [0.41 0.64 0.75 ... 0.16 0.   0.6 ]
 [0.74 0.05 0.4  ... 0.53 0.6  0.  ]]


#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place? 
(**hint**: astype(copy=False))

In [53]:
a=np.arange(5, dtype=np.float32)
b=a.astype(np.int32,copy=False)
print(a)
print(b)

[0. 1. 2. 3. 4.]
[0 1 2 3 4]


#### 54. How to read the following file? (★★☆) 
(**hint**: np.genfromtxt)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [54]:
from io import StringIO
f=StringIO("""1, 2, 3, 4, 5\n
                6,  ,  , 7, 8\n
                 ,  , 9,10,11\n""")
z=np.genfromtxt(f, delimiter=",", dtype=int,missing_values=0)
print(z)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆) 
(**hint**: np.ndenumerate, np.ndindex)

In [55]:
e=np.arange(8).reshape(2,2,2)
for index,value in np.ndenumerate(e):
    print(index, value)
for index in np.ndindex(e.shape):
    print(index, e[index])

(0, 0, 0) 0
(0, 0, 1) 1
(0, 1, 0) 2
(0, 1, 1) 3
(1, 0, 0) 4
(1, 0, 1) 5
(1, 1, 0) 6
(1, 1, 1) 7
(0, 0, 0) 0
(0, 0, 1) 1
(0, 1, 0) 2
(0, 1, 1) 3
(1, 0, 0) 4
(1, 0, 1) 5
(1, 1, 0) 6
(1, 1, 1) 7


#### 56. Generate a generic 2D Gaussian-like array (★★☆) 
(**hint**: np.meshgrid, np.exp)

In [56]:
x,y=np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
d=np.sqrt(x*x+y*y)
sigma,mu=1.0, 0.0
g=np.exp(-((d-mu)**2/(2.0*sigma**2)))
print(g)

[[0.37 0.45 0.52 0.57 0.6  0.6  0.57 0.52 0.45 0.37]
 [0.45 0.55 0.63 0.7  0.73 0.73 0.7  0.63 0.55 0.45]
 [0.52 0.63 0.73 0.81 0.85 0.85 0.81 0.73 0.63 0.52]
 [0.57 0.7  0.81 0.89 0.94 0.94 0.89 0.81 0.7  0.57]
 [0.6  0.73 0.85 0.94 0.99 0.99 0.94 0.85 0.73 0.6 ]
 [0.6  0.73 0.85 0.94 0.99 0.99 0.94 0.85 0.73 0.6 ]
 [0.57 0.7  0.81 0.89 0.94 0.94 0.89 0.81 0.7  0.57]
 [0.52 0.63 0.73 0.81 0.85 0.85 0.81 0.73 0.63 0.52]
 [0.45 0.55 0.63 0.7  0.73 0.73 0.7  0.63 0.55 0.45]
 [0.37 0.45 0.52 0.57 0.6  0.6  0.57 0.52 0.45 0.37]]


#### 57. How to randomly place p elements in a 2D array? (★★☆) 
(**hint**: np.put, np.random.choice)

In [57]:
n=4
p=3
z=np.zeros((n,n))
np.put(z,np.random.choice(arange(n*n), p, replace=False),1)
print(z)

[[0. 0. 0. 1.]
 [0. 0. 0. 0.]
 [0. 0. 0. 1.]
 [1. 0. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆) 
(**hint**: mean(axis=,keepdims=))

In [58]:
x=np.random.rand(5,5)
print(x)
y=x-x.mean(axis=1, keepdims=True)
# y=x-x.mean(axis=1).reshape(-1, 1)
print(y)

[[0.32 0.19 0.06 0.62 0.02]
 [0.79 0.27 0.21 0.58 0.61]
 [0.5  0.03 0.69 0.39 0.72]
 [0.68 0.18 0.07 0.17 0.7 ]
 [0.29 0.3  0.74 0.19 0.04]]
[[ 0.08 -0.05 -0.18  0.38 -0.22]
 [ 0.3  -0.22 -0.28  0.09  0.12]
 [ 0.04 -0.44  0.23 -0.08  0.25]
 [ 0.32 -0.18 -0.29 -0.19  0.34]
 [-0.02 -0.01  0.43 -0.13 -0.27]]


#### 59. How to sort an array by the nth column? (★★☆) 
(**hint**: argsort)

In [59]:
z=np.random.randint(0,10,(3,3))
print(z)
print(z[z[:,1].argsort()])

[[9 5 9]
 [8 0 9]
 [5 7 5]]
[[8 0 9]
 [9 5 9]
 [5 7 5]]


#### 60. How to tell if a given 2D array has null columns? (★★☆) 
(**hint**: any, ~)

In [60]:
Z=np.random.randint(0,3,(3,3))
print(Z)
print((~Z.any(axis=1)).any())

[[2 0 0]
 [0 2 0]
 [1 0 2]]
False


#### 61. Find the nearest value from a given value in an array (★★☆) 
(**hint**: np.abs, argmin, flat)

In [61]:
f=np.random.randint(0,15,(3,3))
print(f)
g=2
h=np.abs(g-f)
print(h)
i=np.argmin(h)
print(i)
k=f.flat[i]
k

[[11  2 10]
 [ 1  1  9]
 [10  9  4]]
[[9 0 8]
 [1 1 7]
 [8 7 2]]
1


2

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆) 
(**hint**: np.nditer)

In [62]:
A=np.arange(3).reshape(3,1)
print(A)
B=np.arange(3).reshape(1,3)
print(B)
it=np.nditer([A,B,None])
print(it)
for x,y,z in it:
  z[...]=x+y
print(it.operands[2])

[[0]
 [1]
 [2]]
[[0 1 2]]
[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆) 
(**hint**: class method)

In [63]:
class Array(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        print(type(obj))
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")
z= Array(np.arange(10), "range_of_10")
print(z.name)

<class '__main__.Array'>
range_of_10


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★) 
(**hint**: np.bincount | np.add.at)

In [64]:
a=np.ones(10)
b=np.random.randint(0,len(a),10)
a+=np.bincount(b,minlength=len(a))
print(a)
np.add.at(a,b,1)
print(a)

[2. 2. 2. 1. 2. 5. 1. 1. 2. 2.]
[3. 3. 3. 1. 3. 9. 1. 1. 3. 3.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★) 
(**hint**: np.bincount)

In [65]:
a=[2,4,6,8,10,12]
b=[1,3,5,7,9,11]
np.bincount(a,b)

array([ 0.,  0.,  1.,  0.,  3.,  0.,  5.,  0.,  7.,  0.,  9.,  0., 11.])


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★) 
(**hint**: np.unique)

In [66]:
w,h=16,16
i=np.random.randint(0,2,(h,w,3)).astype(np.ubyte)
f=i[...,0]*(256*256)+i[...,1]*256+i[...,2]
n=len(np.unique(f))
print(n)

8


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★) 
(**hint**: sum(axis=(-2,-1)))

In [67]:
a = np.random.randint(0,10,(3,4,3,4))
sum = a.sum(axis=(-2,-1))
print(sum)
sum = a.reshape(a.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)

[[63 48 54 53]
 [57 69 53 51]
 [61 48 56 72]]
[[63 48 54 53]
 [57 69 53 51]
 [61 48 56 72]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★) 
(**hint**: np.bincount)

In [68]:
D=np.random.uniform(0,1,100)
S=np.random.randint(1,10,100)
D_sum=np.bincount(S, weights=D)
D_count=np.bincount(S)
D_mean=D_sum/D_count
print(D_mean)
import pandas as pd
print(pd.Series(D).groupby(S).mean())

[ nan 0.49 0.65 0.62 0.49 0.47 0.48 0.48 0.4  0.52]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: RuntimeWarning: invalid value encountered in true_divide
  """


1    0.487434
2    0.654432
3    0.621634
4    0.493451
5    0.469651
6    0.484798
7    0.484326
8    0.398132
9    0.523808
dtype: float64


#### 69. How to get the diagonal of a dot product? (★★★) 
(**hint**: np.diag)

In [69]:
a=np.random.randint(0,7,(2,2))
b=np.random.randint(0,10,(2,2))
np.diag(np.dot(a,b))

array([40, 21])

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★) 
(**hint**: array\[::4\])

In [70]:
v=np.array([1,2,3,4,5])
zn=3
x=np.zeros(len(v)+(len(v)-1)*zn)
x[::zn+1]=v
x


array([1., 0., 0., 0., 2., 0., 0., 0., 3., 0., 0., 0., 4., 0., 0., 0., 5.])

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★) 
(**hint**: array\[:, :, None\])

In [71]:
a=np.random.randint(1,10,(5,5,3))
b=np.random.randint(1,10,(5,5))
print(a*b[:,:,None])

[[[24 40 40]
  [ 9 54 27]
  [49  7 42]
  [35 63 63]
  [36 72 45]]

 [[12  2  2]
  [49 63 49]
  [30 18 24]
  [32 64 32]
  [40 40 25]]

 [[24 18  6]
  [ 6  1  7]
  [ 8 18  4]
  [56 49 21]
  [20 10  5]]

 [[15 18  9]
  [ 7  7  8]
  [ 6  9  6]
  [20 32 16]
  [56  8 32]]

 [[63 56 56]
  [15 15 30]
  [ 2  6 18]
  [ 6 10  8]
  [48 30  6]]]


#### 72. How to swap two rows of an array? (★★★) 
(**hint**: array\[\[\]\] = array\[\[\]\])

In [72]:
a=np.random.randint(1,5,(4,4))
print(a)
a[[0,1]]=a[[1,0]]
a

[[1 1 2 1]
 [1 1 3 4]
 [3 3 2 1]
 [3 4 4 4]]


array([[1, 1, 3, 4],
       [1, 1, 2, 1],
       [3, 3, 2, 1],
       [3, 4, 4, 4]])

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★) 
(**hint**: repeat, np.roll, np.sort, view, np.unique)

In [73]:
faces=np.random.randint(0,100,(10,3))
f=np.roll(faces.repeat(2,axis=1),-1,axis=1)
f=f.reshape(len(f)*3,2)
F=np.sort(f,axis=1)
g=f.view(dtype=[('p0',f.dtype),('p1',f.dtype)] )
g=np.unique(g)
print(g)

[( 1,  2) ( 2, 50) ( 2, 87) ( 7, 64) (18, 74) (24, 94) (25, 95) (29, 95)
 (30, 99) (31, 29) (32, 61) (37, 25) (50,  1) (51, 18) (55, 24) (56, 32)
 (57,  7) (61, 30) (61, 56) (64, 57) (66, 78) (69,  2) (74, 51) (76, 66)
 (78, 76) (87, 69) (94, 55) (95, 31) (95, 37) (99, 61)]


#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★) 
(**hint**: np.repeat)

In [74]:
a=np.bincount([1,3,5,7,10,2,4])
b=np.repeat(np.arange(len(a)),a)
print(b)

[ 1  2  3  4  5  7 10]


#### 75. How to compute averages using a sliding window over an array? (★★★) 
(**hint**: np.cumsum)

In [75]:
def moving_average(a,n=3) :
    ret=np.cumsum(a, dtype=float)
    ret[n:]=ret[n:] - ret[:-n]
    return ret[n - 1:] / n
a=np.arange(20)
moving_average(a)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18.])

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★) 
(**hint**: from numpy.lib import stride_tricks)

In [76]:
from numpy.lib import stride_tricks
def rolling(a, window):
    shape=(a.size - window + 1, window)
    strides=(a.itemsize, a.itemsize)
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z=rolling(np.arange(9), 5)
print(Z)

[[0 1 2 3 4]
 [1 2 3 4 5]
 [2 3 4 5 6]
 [3 4 5 6 7]
 [4 5 6 7 8]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★) 
(**hint**: np.logical_not, np.negative)

In [78]:
a=np.random.randint(0,1,20)
print(np.logical_not(a,out=a))
print(np.negative(a, out=a))

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
[-1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1]


#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

In [79]:
def distance(P0,P1,p):
    t=P1 - P0
    l=(t**2).sum(axis=1)
    u=-((P0[:,0]-p[...,0])*t[:,0] + (P0[:,1]-p[...,1])*t[:,1]) / l
    u=u.reshape(len(u),1)
    d=P0+u*t-p
    return np.sqrt((d**2).sum(axis=1))
P0=np.random.uniform(-10,10,(10,2))
P1=np.random.uniform(-10,10,(10,2))
p=np.random.uniform(-10,10,( 1,2))
distance(P0, P1, p)

array([ 2.19, 11.02, 11.47,  7.54,  6.95,  5.59, 10.89, 13.28,  5.19,
        3.05])

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

In [80]:
np.array([distance(P0,P1,p_i) for p_i in p])

array([[ 2.19, 11.02, 11.47,  7.54,  6.95,  5.59, 10.89, 13.28,  5.19,
         3.05]])

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★) 
(**hint**: minimum, maximum)

In [81]:
Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)
R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)
R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2
R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()
r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print(Z)
print(R)

[[1 5 8 1 1 0 6 8 9 2]
 [6 4 3 0 8 8 6 0 5 3]
 [9 7 0 7 6 1 0 3 6 4]
 [1 4 1 8 7 4 8 2 6 6]
 [1 8 7 8 6 8 0 3 1 4]
 [1 3 5 9 3 4 0 3 6 0]
 [7 9 4 6 9 4 4 6 5 5]
 [2 1 4 7 8 7 7 5 7 3]
 [4 5 8 0 8 1 9 2 8 4]
 [6 9 6 8 3 4 7 2 9 2]]
[[0 0 0 0 0]
 [0 1 5 8 1]
 [0 6 4 3 0]
 [0 9 7 0 7]
 [0 1 4 1 8]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:19: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.


#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [87]:
Z=np.arange(1,15,dtype=np.uint32)
stride_tricks.as_strided(Z,(11,4),(4,4))

array([[ 1,  2,  3,  4],
       [ 2,  3,  4,  5],
       [ 3,  4,  5,  6],
       [ 4,  5,  6,  7],
       [ 5,  6,  7,  8],
       [ 6,  7,  8,  9],
       [ 7,  8,  9, 10],
       [ 8,  9, 10, 11],
       [ 9, 10, 11, 12],
       [10, 11, 12, 13],
       [11, 12, 13, 14]], dtype=uint32)

#### 82. Compute a matrix rank (★★★) 
(**hint**: np.linalg.svd) (suggestion: np.linalg.svd)

In [90]:
Z=np.random.uniform(0,1,(10,10))
U,S,V=np.linalg.svd(Z)
rank=np.sum(S > 1e-10)
print(rank)

10


#### 83. How to find the most frequent value in an array? 
(**hint**: np.bincount, argmax)

In [93]:
a=np.random.randint(1,10,5)
print(np.bincount(a))
np.bincount(a).argmax()

[0 1 0 1 1 0 0 0 0 2]


9

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [96]:
X=np.random.randint(0,5,(10,10))
n=3
i=1+(X.shape[0]-3)
j=1+(X.shape[1]-3)
C=stride_tricks.as_strided(X, shape=(i, j, n, n), strides=X.strides + X.strides)
print(C)

[[[[0 4 0]
   [4 3 0]
   [2 1 2]]

  [[4 0 0]
   [3 0 2]
   [1 2 1]]

  [[0 0 1]
   [0 2 3]
   [2 1 3]]

  [[0 1 2]
   [2 3 4]
   [1 3 3]]

  [[1 2 1]
   [3 4 1]
   [3 3 3]]

  [[2 1 1]
   [4 1 0]
   [3 3 3]]

  [[1 1 4]
   [1 0 2]
   [3 3 0]]

  [[1 4 1]
   [0 2 2]
   [3 0 0]]]


 [[[4 3 0]
   [2 1 2]
   [4 4 4]]

  [[3 0 2]
   [1 2 1]
   [4 4 2]]

  [[0 2 3]
   [2 1 3]
   [4 2 2]]

  [[2 3 4]
   [1 3 3]
   [2 2 2]]

  [[3 4 1]
   [3 3 3]
   [2 2 3]]

  [[4 1 0]
   [3 3 3]
   [2 3 1]]

  [[1 0 2]
   [3 3 0]
   [3 1 0]]

  [[0 2 2]
   [3 0 0]
   [1 0 3]]]


 [[[2 1 2]
   [4 4 4]
   [0 3 3]]

  [[1 2 1]
   [4 4 2]
   [3 3 4]]

  [[2 1 3]
   [4 2 2]
   [3 4 4]]

  [[1 3 3]
   [2 2 2]
   [4 4 2]]

  [[3 3 3]
   [2 2 3]
   [4 2 2]]

  [[3 3 3]
   [2 3 1]
   [2 2 3]]

  [[3 3 0]
   [3 1 0]
   [2 3 2]]

  [[3 0 0]
   [1 0 3]
   [3 2 1]]]


 [[[4 4 4]
   [0 3 3]
   [1 0 3]]

  [[4 4 2]
   [3 3 4]
   [0 3 4]]

  [[4 2 2]
   [3 4 4]
   [3 4 0]]

  [[2 2 2]
   [4 4 2]
   [4 0 2]]

  [[2 2 3]
   

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★) 
(**hint**: class method)

In [97]:
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)
def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)
X = symetric(np.random.randint(0,10,(5,5)))
X[2,3] = 42
print(X)

[[ 2  4  6  8  5]
 [ 4  0  5 12  4]
 [ 6  5  2 42  7]
 [ 8 12 42  9 15]
 [ 5  4  7 15  6]]


#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★) 
(**hint**: np.tensordot)

In [99]:
p,n= 10, 20
M=np.ones((p,n,n))
V=np.ones((p,n,1))
X=np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(X)

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★) 
(**hint**: np.add.reduceat)

In [103]:
Z=np.ones((16,16))
k=4
S=np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                                       np.arange(0, Z.shape[1], k), axis=1)
print(S)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [104]:
def iterate(Z):
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z
Z = np.random.randint(0,2,(50,50))
for i in range(10): Z = iterate(Z)
print(Z)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


#### 89. How to get the n largest values of an array (★★★) 
(**hint**: np.argsort | np.argpartition)

In [109]:
Z = np.arange(150)
np.random.shuffle(Z)
n = 5
print (Z[np.argsort(Z)[-n:]])
print (Z[np.argpartition(-Z,n)[:n]])

[145 146 147 148 149]
[146 148 147 149 145]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★) 
(**hint**: np.indices)

In [106]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)
    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T
    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]
    return ix
print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


#### 91. How to create a record array from a regular array? (★★★) 
(**hint**: np.core.records.fromarrays)

In [111]:
x=np.array([("hello",2.5,3),
            ("karthick",3.6,2)])
r=np.core.records.fromarrays(x.T,names='col1,col2,col3',formats='S8,f8,i8')
print(r)

[(b'hello', 2.5, 3) (b'karthick', 3.6, 2)]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★) 
(**hint**: np.power, \*, np.einsum)

In [112]:
x=np.random.random(int(5e7))
%timeit np.power(x,3)
%timeit x*x*x
%timeit np.einsum('i,i,i->i',x,x,x)

1 loop, best of 5: 3.75 s per loop
10 loops, best of 5: 139 ms per loop
10 loops, best of 5: 123 ms per loop


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★) 
(**hint**: np.where)

In [113]:
A=np.random.randint(0,5,(8,3))
B=np.random.randint(0,5,(2,2))
C=(A[..., np.newaxis, np.newaxis] == B)
rows=np.where(C.any((3,1)).all(1))[0]
print(rows)

[1 2 3 4 6 7]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

In [114]:
M=np.random.randint(0,5,(10,3))
print(M)
E=np.all(M[:,1:] == M[:,:-1], axis=1)
U=M[~E]
print(U)
U=M[M.max(axis=1) != M.min(axis=1),:]
print(U)

[[3 3 4]
 [2 3 4]
 [1 0 1]
 [4 2 3]
 [4 4 4]
 [0 1 2]
 [1 0 4]
 [3 3 2]
 [3 4 4]
 [0 0 0]]
[[3 3 4]
 [2 3 4]
 [1 0 1]
 [4 2 3]
 [0 1 2]
 [1 0 4]
 [3 3 2]
 [3 4 4]]
[[3 3 4]
 [2 3 4]
 [1 0 1]
 [4 2 3]
 [0 1 2]
 [1 0 4]
 [3 3 2]
 [3 4 4]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★) 
(**hint**: np.unpackbits)

In [115]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
B = ((I.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
print(B[:,::-1])
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(I[:, np.newaxis], axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]
[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★) 
(**hint**: np.ascontiguousarray)

In [117]:
Z = np.random.randint(0,21(5,5))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print(uZ)
uZ = np.unique(Z, axis=0)
print(uZ)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★) 
(**hint**: np.einsum)

In [118]:
A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)
np.einsum('i->', A)       
np.einsum('i,i->i', A, B) 
np.einsum('i,i', A, B)    
np.einsum('i,j->ij', A, B)

array([[0.1 , 0.16, 0.44, 0.43, 0.74, 0.87, 0.5 , 0.52, 0.71, 0.56],
       [0.1 , 0.16, 0.42, 0.42, 0.72, 0.84, 0.49, 0.51, 0.69, 0.54],
       [0.11, 0.17, 0.47, 0.47, 0.8 , 0.94, 0.54, 0.56, 0.77, 0.6 ],
       [0.01, 0.01, 0.04, 0.04, 0.07, 0.08, 0.04, 0.05, 0.06, 0.05],
       [0.03, 0.05, 0.15, 0.15, 0.25, 0.3 , 0.17, 0.18, 0.24, 0.19],
       [0.11, 0.18, 0.49, 0.48, 0.83, 0.97, 0.56, 0.58, 0.79, 0.62],
       [0.07, 0.11, 0.31, 0.31, 0.52, 0.61, 0.35, 0.37, 0.5 , 0.39],
       [0.03, 0.05, 0.13, 0.12, 0.21, 0.25, 0.14, 0.15, 0.2 , 0.16],
       [0.01, 0.02, 0.04, 0.04, 0.07, 0.09, 0.05, 0.05, 0.07, 0.05],
       [0.05, 0.08, 0.21, 0.21, 0.36, 0.43, 0.25, 0.26, 0.35, 0.27]])

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)? 
(**hint**: np.cumsum, np.interp)

In [119]:
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)
dr = (np.diff(x)**2 + np.diff(y)**2)**.5
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)                
r_int = np.linspace(0, r.max(), 200) 
x_int = np.interp(r_int, r, x)       
y_int = np.interp(r_int, r, y)

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★) 
(**hint**: np.logical\_and.reduce, np.mod)

In [120]:
X=np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n=4
M=np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M&=(X.sum(axis=-1) == n)
print(X[M])

[[2. 0. 1. 1.]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★) 
(**hint**: np.percentile)

In [121]:
X=np.random.randn(100) 
N=1000 
idx=np.random.randint(0, X.size, (N, X.size))
means=X[idx].mean(axis=1)
confint=np.percentile(means, [2.5, 97.5])
print(confint)

[-0.2   0.13]
